### ISSUE TITLE
Version of Nextjs

### ISSUE THREAD

**Issue by ratracegrad** [leap-ai/headshots-starter#10]
I cloned the repo and ran `npm install`.  This installs the latest version of `next.js`.  I am getting two errors when I run `npm run dev`.

- warn  - You have enabled the experimental feature (serverActions) in next.config.js.
warn  - Experimental features are not covered by Semver, and may cause unexpected or broken application behavior. Use at your own risk.
- Couldn't find a `pages` directory. Please create one under the project root

Could you tell me what version you used initially to create headshots-starter? I would like to install that specific version so I can get your repo up and running.

Thanks.

**Comment by Marfuen** [comment]
@ratracegrad Hi, can you try using `"next": "^13.5.1"`, also we used yarn.

**Comment by ratracegrad** [comment]
Thank you for the quick response. Updating the version of next.js to `^13.5.1` solved the problem
