### ISSUE TITLE
Could not authenticate user

### ISSUE THREAD

**Issue by johanguse** [leap-ai/headshots-starter#2]
I can't create an account on the demo website, Could you add forgot password function?

![image](https://github.com/leap-ai/headshots-starter/assets/6184866/6d103140-2b17-441f-9b48-1e9cfaca4f9d)

**Comment by claudfuen** [comment]
@johanguse Did you try clicking "sign up" first? I know the UX here isn't ideal.

Clicking sign up should've sent you an email confirmation to activate your account.

**Comment by Marfuen** [comment]
@johanguse Can you provide more details on your issue? I've tried logging in with a fresh account and I had no issues.

Did you verify your email after signing up?

**Comment by Marfuen** [comment]
@johanguse I can also send you a password recovery email, if you want

**Comment by johanguse** [comment]
@Marfuen I guess I've verified my email... could you send the password recovery email?

**Comment by Marfuen** [comment]
@johanguse Sent a link

**Comment by Marfuen** [comment]
We are using magic link now
