### ISSUE TITLE
Credit Points are not set/saved in the credits table

### ISSUE THREAD

**Issue by dongle132** [leap-ai/headshots-starter#37]
I was able to setup everything including the credit table but the only value that is not saved/updated is the total number of credits.

The entry is created in the credits table and the user_id is correct:
![image](https://github.com/leap-ai/headshots-starter/assets/31986934/38c6d33a-96ee-418c-bc2a-79c1f19d0bb1)

RLS is set (tried it also without RLS):
![image](https://github.com/leap-ai/headshots-starter/assets/31986934/99366e18-d1d7-4f52-a852-1dbed3ed8f75)

Wihtin the API-logs from supabase I can see couple of these entries:
![image](https://github.com/leap-ai/headshots-starter/assets/31986934/5bb41e02-5e88-4d03-88ce-9c8207f1a88e)

Thanks in advance for your help!

**Comment by Marfuen** [comment]
Where is this hosted, vercel? @dongle132 You can check the vercel logs and see if you're getting an error

**Comment by dongle132** [comment]
Yes this is hosted by VERCEL ... just tried it again but in VERCEL I can only see these 4x entries and no credits are saved in the credits table:

![image](https://github.com/leap-ai/headshots-starter/assets/31986934/2f75794c-4e4a-4e2a-82c5-0ed736ceba56)

**Comment by Marfuen** [comment]
I'm guessing your webhook url is set incorrectly, have you checked your environment variables? You also need to setup the webhook on Stripe, did you do that?

**Comment by Marfuen** [comment]
Did you setup the stripe webhook?

**Comment by dongle132** [comment]
Nope I've setup everything correct. After I've read through all the code I've found the error and fixed it.  
The problem is (unfort) on your side =) 

In the ENV.LOCAL File you define the stripe product VARS like this:
![image](https://github.com/leap-ai/headshots-starter/assets/31986934/e2eab9b5-6ed9-467e-8a4b-925c9a9c859a)


BUT in the stripe-webhook you call the 3x and 5x credit VARS with an **S** at the end. As soon as you remove the S everything works:
![image](https://github.com/leap-ai/headshots-starter/assets/31986934/cde635bb-5ad2-41e7-8090-e56f7f8f1331)

**Comment by dongle132** [comment]
FIXED

**Comment by Marfuen** [comment]
Oh, I'll update the readme to fix that. Glad you found out what it was!
