### ISSUE TITLE
Error when is stripe enabled false

### ISSUE THREAD

**Issue by NathBabs** [leap-ai/headshots-starter#44]
During deployment, it would fail on vercel when there are no optional variables like the STRIPE and RESEND variables...anyway i just had to put in dummy values so it can deploy.

When deployment was successful and i tried to train a model, it kept saying something went wrong, so i went to check the application logs in vercel and this is the error i was seeing

```bash
{ stripeIsConfigured: false }
TypeError: Cannot read properties of undefined (reading 'map')
    at POST (/var/task/.next/server/app/leap/train-model/route.js:298:97)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/task/.next/server/chunks/778.js:5600:37
```

Please what could be the issue ?

**Comment by Marfuen** [comment]
@NathBabs Are you still seeing this issue?

**Comment by NathBabs** [comment]
> @NathBabs Are you still seeing this issue?

@Marfuen yes I am .

![Screenshot_20231009_210224_Chrome](https://github.com/leap-ai/headshots-starter/assets/17989552/55601c34-4fc5-433d-8798-91befb955929)

**Comment by Marfuen** [comment]
Can you add console logs in that file to see what the issue could be? before the .map

**Comment by chinmaykunkikar** [comment]
Hey @Marfuen,
I'm having the same error. This is what I got:

```bash
- event compiled successfully in 139 ms (663 modules)
http://localhost:3000/leap/train-webhook <--- I added "VERCEL_URL=localhost:3000" to .env.local and logged it here
 
{ stripeIsConfigured: false }
{
  message: [ 'webhookUrl must be a URL address' ],
  error: 'Bad Request',
  statusCode: 400
}
TypeError: Body is unusable
    at specConsumeBody (node:internal/deps/undici/undici:6630:15)
    at Response.json (node:internal/deps/undici/undici:6533:18)
    at POST (webpack-internal:///(rsc)/./app/leap/train-model/route.ts:123:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:254:37)
^C
```


Then I used [localtunnel (an alternative to ngrok](https://theboroer.github.io/localtunnel-www/) and replaced `VERCEL_URL` with that address.
I got a new error with that:

```bash
http://red-yaks-trade.loca.lt/leap/train-webhook
{ stripeIsConfigured: false }
{
  statusCode: 402,
  message: 'Training models is only available on paid plans. Please upgrade to a paid account to use this feature.'
}
TypeError: Body is unusable
    at specConsumeBody (node:internal/deps/undici/undici:6630:15)
    at Response.json (node:internal/deps/undici/undici:6533:18)
    at POST (webpack-internal:///(rsc)/./app/leap/train-model/route.ts:123:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:254:37)
```

It asks me to use a paid plan. Is that normal?

**Comment by chinmaykunkikar** [comment]
Update: I tried it on the [leap API playground](https://reference.tryleap.ai/reference/train). It's indeed true that it will require me to pay to train models.

![image](https://github.com/leap-ai/headshots-starter/assets/6230769/0a476d1f-dffc-4922-8828-e9206eaf19b1)

**Comment by NathBabs** [comment]
@chinmaykunkikar yes I tried training on Leap's website some minutes ago and it said it was for paid users.

@Marfuen

**Comment by Marfuen** [comment]
@NathBabs Yeah, training models costs a lot since we have to use GPU's so we can't give that away for free. You will have to create an API key with Leap first.

**Comment by NathBabs** [comment]
> @NathBabs Yeah, training models costs a lot since we have to use GPU's so we can't give that away for free. You will have to create an API key with Leap first.

@Marfuen but this wasn't stated in the setup , that we have to pay for training on Leap
