### ISSUE TITLE
postgress stuff

### ISSUE THREAD

**Issue by rossman22590** [leap-ai/headshots-starter#50]
(node:8) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{ stripeIsConfigured: false }
{
  code: 'PGRST204',
  details: null,
  hint: null,
  message: "Column 'modelId' of relation 'models' does not exist"
}

**Comment by rossman22590** [comment]
-- Create the models table first since it's referenced by other tables
CREATE TABLE models (
    id INT8 PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id),
    status TEXT NOT NULL,
    modelId TEXT -- No need for unique constraint on this column anymore
);

-- Create the images table
CREATE TABLE images (
    id INT8 PRIMARY KEY,
    modelId INT8 REFERENCES models(id),
    uri TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the samples table
CREATE TABLE samples (
    id INT8 PRIMARY KEY,
    uri TEXT NOT NULL,
    modelId INT8 REFERENCES models(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the credits table
CREATE TABLE credits (
    id INT8 PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    credits INT8 NOT NULL, -- Assuming credits is an integer field
    user_id UUID REFERENCES auth.users(id)
);

**Comment by rossman22590** [comment]
![image](https://github.com/leap-ai/headshots-starter/assets/6137292/a6fa0207-7e20-4ed5-a5c3-62ced5f6a58a)

**Comment by abhayjb** [comment]
Is your link from images modelId to models missing ?

**Comment by rossman22590** [comment]
Seems know know how to fix this or do you have a schema I can use ?

**Comment by Marfuen** [comment]
Hey @rossman22590 , we just added a migration file for supabase that can handle everything for you. If you want to run this on your Supabase SQL Dashboard, or run it locally while linking to it, it will handle your table creations / policies

https://github.com/leap-ai/headshots-starter/blob/main/supabase/migrations/20231010160942_remote_schema.sql

**Comment by rossman22590** [comment]
ok so you are actually amazing ty - it works now

**Comment by rossman22590** [comment]
ok now im stuck on the screen it says its training , but i got email saying its done

**Comment by Marfuen** [comment]
@rossman22590 The UI could be cached

**Comment by rossman22590** [comment]
i wish its been going  for 6 hours and i went to anew machine

**Comment by rossman22590** [comment]
how can i fix it ?
i was charged, its pending for 2 days but on leap it has finsihed
