### ISSUE TITLE
Error running on local when stripe is not configured

### ISSUE THREAD

**Issue by abhayjb** [leap-ai/headshots-starter#51]
(node:86725) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
{ stripeIsConfigured: false }
{
  code: '23502',
  details: null,
  hint: null,
  message: 'null value in column "status" of relation "models" violates not-null constraint'
}

1. Supabase configured - Done
2. npm run dev - Done
3. http://localhost:3000 - Page rendering - Done
4. magic received in email - Done
5. images uploaded - Done
6. click train model - this error appears

**Comment by lok0919** [comment]
Either allow the `status` field in the `models` table to be empty or set the status value during insert.

But then you may run into another problem when running it locally. Leap AI does not accept any callback URLs with `localhost`, so you can use [Localtunnel](https://theboroer.github.io/localtunnel-www/) to expose your application to Leap for callbacks

If you are not subscribed to any plan, you should receive the error from Leap after all the setup.
`{"statusCode":402,"message":"Training models is only available on paid plans. Please upgrade to a paid account to use this feature."}`

**Comment by abhayjb** [comment]
Thanks lok919,

allowing `status` to be empty also throws another error

used [Localtunnel](https://theboroer.github.io/localtunnel-www/) to expose localhost for callbacks. The url provided is valid for the node runtime, while I have to run run the app in dev which is a seperate runtime. now trying to find how two node runtimes can be run in parallel

havent reached there yet for the training model to check for paid plans
