### ISSUE TITLE
Simplify Supabase Setup

### ISSUE THREAD

**Issue by thorwebdev** [leap-ai/headshots-starter#54]
Hey, awesome starter project! To make the configuration easier for everyone, could you do the following steps, please?

* Delete the `supabase` folder
* Run `supabase init` (make sure you have the latest version of the Supabase CLI installed!)
* Run `supabase link --project-ref ********************` with your Supabase project id [ref](https://supabase.com/docs/reference/cli/supabase-link)
* Run `supabase db pull --linked` [ref](https://supabase.com/docs/reference/cli/supabase-db-pull)

This will create a migration file with all the schema and RLS policies included, making the setup a lot easier for everyone. Once finished, make sure to commit the generated migration files and update your deploy button URL to include the supabase integration which will automatically set up the schema for folks when deploying to vercel: 

### Generate the deploy button

Use Vercel’s [deploy button generator](https://vercel.com/docs/concepts/deployments/deploy-button#generate-your-own) to create a 1-click deploy button for your template. Set the Supabase relevant parameters as follows:

- Git Repository: set this to the root of your Next.js/Svelte/Vue etc app. Different branches and Monorepos are also supported. E.g. [`https://github.com/vercel/nextjs-subscription-payments/tree/main`](https://github.com/vercel/nextjs-subscription-payments/tree/main)
- Environment Variables: set any non-supabase environment variables required for your template. Remember the Supabase specific env vars will automatically be set and kept up to date by our integration.
- Integrations
    - Integration IDs: Add `oac_VqOgBHqhEoFTPzGkPd7L0iH6` to make sure the Supabase Integration will be installed.
    - External ID: Set this to the root of your project where the `/supabase` folder is located. Make sure to include `/tree/branchname` here even if it’s on the main branch! This is crucial for the integration to fetch the migration and seed files. E.g. `https://github.com/vercel/nextjs-subscription-payments/tree/main`

**Comment by Marfuen** [comment]
@thorwebdev Awesome, will do

**Comment by Marfuen** [comment]
@thorwebdev I can't seem to get the Supabase integration working, Once I click Create Project it errors and stays in an infinite loading screen.

Errors I see in the network tab:
403 Forbidden: https://api.supabase.io/platform/integrations/vercel/connections/9189f915-39f8-4123-be76-f8edbca9a3ce/sync-envs (    "message": "{\"error\":{\"code\":\"forbidden\",\"message\":\"Not authorized\"}}"
)
403 Forbidden: https://api.supabase.io/platform/integrations/vercel/projects/8beb2178-2f25-4a0e-bf3a-e73afb9bd5a9?limit=1000 (    "message": "{\"error\":{\"code\":\"forbidden\",\"message\":\"Not authorized\"}}"
)
406 Not Acceptable
https://api.supabase.io/platform/integrations/vercel/projects/8beb2178-2f25-4a0e-bf3a-e73afb9bd5a9?limit=1000 (    "message": "Failed to retrieve vercel organization integration with the given id"
)


Here's my vercel button code:
[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fleap-ai%2Fheadshots-starter%2Ftree%2Fmariano-simplify-setup&env=LEAP_API_KEY,LEAP_WEBHOOK_SECRET,RESEND_API_KEY,STRIPE_SECRET_KEY,STRIPE_WEBHOOK_SECRET,STRIPE_PRICE_ID_ONE_CREDIT,STRIPE_PRICE_ID_THREE_CREDITS,STRIPE_PRICE_ID_FIVE_CREDITS,NEXT_PUBLIC_STRIPE_IS_ENABLED,SUPABASE_SERVICE_ROLE_KEY&envDescription=API%20Keys%20needed%20to%20run%20all%20features&envLink=https%3A%2F%2Fgithub.com%2Fleap-ai%2Fheadshots-starter%2Ftree%2Fmariano-simplify-setup%2F.env.local.example&integration-ids=oac_VqOgBHqhEoFTPzGkPd7L0iH6&external-id=https%3A%2F%2Fgithub.com%2Fleap-ai%2Fheadshots-starter%2Ftree%2Fmariano-simplify-setup)

**Comment by Marfuen** [comment]
Actually I just noticed that it did create the tables, but the modal to finish creating the project, is stuck in an infinite loading state.

**Comment by alexschachne** [comment]
Implemented!
