### ISSUE TITLE
Error with DynamicServerError deploying in Vercel

### ISSUE THREAD

**Issue by paulcull** [leap-ai/headshots-starter#60]
Hi,

I have an issue deploying in vercel.

<html>
<body>

$ next build
--
19:39:48.292 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
19:39:48.293 | This information is used to shape Next.js' roadmap and prioritize features.
19:39:48.293 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
19:39:48.293 | https://nextjs.org/telemetry
19:39:48.293 |  
19:39:48.383 | Creating an optimized production build ...
19:40:02.951 | ✓ Compiled successfully
19:40:02.951 | Linting and checking validity of types ...
19:40:09.465 | Collecting page data ...
19:40:12.577 | Generating static pages (0/9) ...
19:40:12.666 | Generating static pages (2/9)
19:40:12.723 | Generating static pages (4/9)
19:40:12.724 | DynamicServerError: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
19:40:12.724 | at staticGenerationBailout (/vercel/path0/.next/server/chunks/859.js:1:3931)
19:40:12.724 | at Object.cookies (/vercel/path0/.next/server/chunks/859.js:1:1519)
19:40:12.724 | at w.getCookie (/vercel/path0/.next/server/chunks/207.js:1:4965)
19:40:12.724 | at w.getItem (/vercel/path0/.next/server/chunks/207.js:1:12982)
19:40:12.725 | at getItemAsync (/vercel/path0/.next/server/chunks/705.js:1:50595)
19:40:12.725 | at SupabaseAuthClient._recoverAndRefresh (/vercel/path0/.next/server/chunks/705.js:1:32089)
19:40:12.725 | at SupabaseAuthClient._initialize (/vercel/path0/.next/server/chunks/705.js:1:11941)
19:40:12.725 | at /vercel/path0/.next/server/chunks/705.js:1:11215
19:40:12.725 | at /vercel/path0/.next/server/chunks/705.js:1:21707
19:40:12.725 | at SupabaseAuthClient.lockNoOp [as lock] (/vercel/path0/.next/server/chunks/705.js:1:8633) {
19:40:12.726 | digest: 'DYNAMIC_SERVER_USAGE'

</body>
</html>

looking up there is workaround using export const dynamic = "force-dynamic" when using cookies, but this is already there in page.tsx

anyone else?

**Comment by Marfuen** [comment]
Hi, @paulcull is this from one of the existing pages or is it a new one you made?

**Comment by paulcull** [comment]
default - just forked and manually manually created the env's - just resync'd fork and same issue

**Comment by Marfuen** [comment]
@paulcull As you mentioned earlier you have to put that export const dynamic code, in the page, not sure which page could be causing this.

**Comment by paulcull** [comment]
last commits seem to have fixed this so closing
