### ISSUE TITLE
Missing row permission for credits table

### ISSUE THREAD

**Issue by Deanstirrat** [leap-ai/headshots-starter#62]
This may be an issue on my end but the supabase setup only allows the service_role to insert rows in the credit table but a new user needs access to create an initial row leap/train-model route. Either that or another supabase client object is needed with service_role permission like is done in the other leap routes. 

Please correct me if I'm wrong. 

<img width="524" alt="Screenshot 2023-10-10 at 1 59 28 PM" src="https://github.com/leap-ai/headshots-starter/assets/37011725/298456c3-3013-4155-a924-98eefbde96ac">

**Comment by Marfuen** [comment]
@Deanstirrat Hey, if you don't mind reseting your database, we actually just generated a supabase migration file that will handle all of the policies for you. 

If you want to reset it and let it do it for you then you can run this migration on your db
https://github.com/leap-ai/headshots-starter/blob/main/supabase/migrations/20231010160942_remote_schema.sql

You can follow their guide here: https://supabase.com/docs/guides/cli/managing-environments

**Comment by Marfuen** [comment]
@Deanstirrat If your issue is specifically with the service role, also, if you instantiated supabase with the service role key, then it should let you insert that first row.

**Comment by Marfuen** [comment]
More info / screenshots could help
