### ISSUE TITLE
Is this PAID?

### ISSUE THREAD

**Issue by Sequential-circuits** [leap-ai/headshots-starter#65]
Looks like even when running locally it needs the services of leap which seem to be always paid for

If that's the case not cool, as this is advertised as open source

Hope I am wrong :)

**Comment by claudfuen** [comment]
Hi @Sequential-circuits! If you have a powerful GPU at home, you can write your own code to run stable diffusion training and inference locally and tweak the code to work with your setup.

Feel free to leverage any parts of the template that are helpful!
