### ISSUE TITLE
do not exist NEXT_PUBLIC_SUPABASE_ANON_KEY ? it do exist

### ISSUE THREAD

**Issue by gstarwd** [leap-ai/headshots-starter#7]
i rename   .env.local.example  as  .env.local 
 and NEXT_PUBLIC_SUPABASE_ANON_KEY is in this file.

but  vercel deploy also come up with the error do not exist NEXT_PUBLIC_SUPABASE_ANON_KEY .
plz help me:

Error: MISSING NEXT_PUBLIC_SUPABASE_ANON_KEY!
--
22:33:20.937 | at 90791 (/vercel/path0/.next/server/app/leap/image-webhook/route.js:167:11)
22:33:20.937 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
22:33:20.937 | at __webpack_exec__ (/vercel/path0/.next/server/app/leap/image-webhook/route.js:316:39)
22:33:20.937 | at /vercel/path0/.next/server/app/leap/image-webhook/route.js:317:74
22:33:20.937 | at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:138:21)
22:33:20.938 | at /vercel/path0/.next/server/app/leap/image-webhook/route.js:317:47
22:33:20.938 | at Object.<anonymous> (/vercel/path0/.next/server/app/leap/image-webhook/route.js:320:3)
22:33:20.938 | at Module._compile (node:internal/modules/cjs/loader:1256:14)
22:33:20.938 | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
22:33:20.939 | at Module.load (node:internal/modules/cjs/loader:1119:32)
22:33:20.939 |  
22:33:20.940 | > Build error occurred
22:33:20.942 | Error: Failed to collect page data for /leap/image-webhook
22:33:20.942 | at /vercel/path0/node_modules/next/dist/build/utils.js:1158:15
22:33:20.942 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
22:33:20.943 | type: 'Error'
22:33:20.945 | }
22:33:21.033 | error Command failed with exit code 1.
22:33:21.034 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:33:21.069 | Error: Command "yarn run build" exited with 1

**Comment by graham-fleming** [comment]
Also get the same error



https://nextjs.org/telemetry
- info Creating an optimized production build...
- info Compiled successfully
- info Linting and checking validity of types...
- info Collecting page data...
Error: MISSING NEXT_PUBLIC_SUPABASE_ANON_KEY!
    at 90791 (/vercel/path0/.next/server/app/leap/image-webhook/route.js:167:11)
    at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)

**Comment by FabianHem** [comment]
Seems like the names of the env-var is wrong, in both train-webhook/route.ts and image-webhook/route.ts the access speaks of 

`const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;`

Either the `NEXT_PUBLIC_SUPABASE_ANON_KEY` variable needs to be renamed to `SUPABASE_SERVICE_ROLE_KEY` or the route.ts files need to change.

**Comment by Marfuen** [comment]
Fixed, changed to anon key now
