### ISSUE TITLE
Feature: Adding contribution section to the readme.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [leap-ai/headshots-starter#79]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The "Contributors" section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/leap-ai/headshots-starter/assets/147402107/53b87cb9-328b-424d-a381-ec23d0040534)

**Comment by Kalyanimhala** [comment]
@Marfuen  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by Marfuen** [comment]
@Kalyanimhala Hey, this would be a great addition, I assigned this task to you then

**Comment by Kalyanimhala** [comment]
Thank You, I'll work on it.
