### ISSUE TITLE
TypeError when iterating through headshots output on train-webhook

### ISSUE THREAD

**Issue by GGalupo** [leap-ai/headshots-starter#97]
If the output from train-webhook endpoint doesn't have enough items to fill `headshots_part_2`, `headshots_part_3` or `headshots_part_4`, a TypeError will be thrown, because it's trying to iterate on `undefined` to create `allHeadshots` const.

This behavior makes the function execution to stop, and images are not saved on the database.

**Output**

![Screenshot_3](https://github.com/leap-ai/headshots-starter/assets/61074472/ebd95956-354b-472e-96b3-2119b69aaf2f)

**Error message on Vercel console**

![Screenshot_2](https://github.com/leap-ai/headshots-starter/assets/61074472/63df18ed-60c7-4e0b-9e32-7cf328d17b5f)

I'll make a PR to fix this issue.

**Comment by Marfuen** [comment]
@GGalupo Hey, so I don't think this is an issue since if you use the headshots template 1:1 and the template workflow this will work.

If someone edits their workflow to not have those outputs then it would be up to them to update their code to show that too
